### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by yu-ka3028** [yu-ka3028/Shibatt#14]
お疲れ様です。
MVPリリースまでの機能実装が完了いたしましたので提出させていただきます。

---

## 各種情報
サービス名：Shibatt
サービスURL：https://tranquil-scrubland-33880-be7a5f13a430.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能(sorcery)
- [x] メモ作成機能: 素早くできるようにページ遷移なし
- [x] メモ一覧機能
- [x] 振り返りメモ作成機能
- [x] 振り返りメモ一覧機能
- [x] メモ/振り返りメモ_編集機能（content,progress） 
- [x] メモ/振り返りメモ_検索機能(ransack)(contentを検索)
- [x] メモ/振り返りメモ_ステータス設定(未完了/完了)
- [ ] ジャンル/タグ機能
- [ ] ステータスを元に振り返り達成率の表示
- [ ] Xでの共有

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください
## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください
- [ ] ジャンル/タグ機能
- [ ] ステータスを元に振り返り達成率の表示
- [ ] Xでの共有

→MVPリリース時点での実装を見送った理由
　：振り返りメモを作成できる点がサービスとして最低限必要な機能であるため

## サービスイメージがわかるようなスクリーンショット等
- メモ一覧画面
![Image 1](https://i.gyazo.com/cd8098e85e58f3e5b3f1a0bb458756fa.png) 
- 振り返りメモ一覧画面
![Image 2](https://i.gyazo.com/be195a07542e0b714141c82939598efb.png) 
- 振り返りメモ編集画面
![Image 3](https://i.gyazo.com/0ac411b9f27bbb324609bf936fdbba06.png)

また、通常ユーザーが触れない画面は現在ございません。
メモ/振り返りメモをあらかじめ入れたIDとPWがこちらです。
ID：mvp@test PW:test

---
以上、
お忙しいところ恐縮です、ご確認お願い申し上げます。

**Comment by Mariko222** [comment]
ご提出ありがとうございます。
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

以下、少し気になった箇所のコメントになります。
***
- ユーザー登録時やメモ作成時に何も入力しないとエラーメッセージなど出なかったので、フラッシュメッセージ等があると分かりやすいかなと思いました。
- 入力項目と作成などのクリック箇所が同じようなテキストになっていて分かりづらいので、フォームやボタンのフォーマットや色味、配置を整えると分かりやすいかなと思いました。
