### ISSUE TITLE
本リリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [yu-ka3028/Shibatt#308]
以下、修正をお願いできればと思います！

1. アプリ上の表記で「英語」「日本語」が混ざっていて、少々UXが悪くなっているイメージなので、まずはどちらかに統一される方がいいかと思いました。
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/3ce2e7cb853889528b606186aa5d5cf1.png)](https://startup-technology.gyazo.com/3ce2e7cb853889528b606186aa5d5cf1)

---

2. ヘッダー左上には、アプリのアイコン（タイトル）が表示されるのが一般的かとおもうので、Xでの共有ではなく、アイコンを置くと違和感がなくなるかと！（Xへの共有はMenuの中でも良さそうです！）
 [![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/01580de6f8d850e74dae0954d4af43b0.png)](https://startup-technology.gyazo.com/01580de6f8d850e74dae0954d4af43b0)

---

3. モーダルで使い方が表示され、イラストでも使い方が表示されているので、モーダル機能は削除して、「使い方」というタイトルだけ残す形でもいいかもです！
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/c8b64fa2dd9f25e9ec52c392f79cbe65.png)](https://startup-technology.gyazo.com/c8b64fa2dd9f25e9ec52c392f79cbe65)

----

4. GIFの部分でエラーが起こってしまったので確認お願いします！
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/47a082957fa8f39cef968466311155b1.gif)](https://startup-technology.gyazo.com/47a082957fa8f39cef968466311155b1)

**Comment by yu-ka3028** [comment]
## 概要

- レビューいただいた修正箇所

## 実装内容
- 変更点
  - [ ] メモ、振り返りメモの日本語英語統一
  - [ ] ヘッダー（Xシェア、アプリアイコン）
  - [ ] 使い方モーダル削除
  - [ ] タグのUpdate不具合

- 追加で変更した内容
  - [ ] 達成率０％表示

## 備考

**Comment by tmtkzk0823** [comment]
ありがとうございます！
確認させていただきました！

確認させていただいている最中に、また気になる箇所があったので、お伝えさせていただければと思います🙇‍♂️

1. LINEログインを使用しない場合のログインでusernameを使用していますが、こちら、modelを見るとunique制約が付いていないように思ったのでご確認お願いします！（違うユーザーでログインしてしまう可能性が出てくるかと思いまして）
 [![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/b6f03af85f6c3f84d40bf7bf574a5cdf.png)](https://startup-technology.gyazo.com/b6f03af85f6c3f84d40bf7bf574a5cdf)

2. 修正していただいたアプリ下部にあるメモ作成などのボタンがフッターの下に隠れてしまっているのでご確認お願いします！
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/b734cc3d4449667297eb88bae47d34f1.gif)](https://startup-technology.gyazo.com/b734cc3d4449667297eb88bae47d34f1)

3. メモ入力フォームですが、バランスが左により過ぎているので、
- 入力フォームを赤枠の大きさに
- 各ボタンの位置を矢印の場所に移動
- 「close」を「閉じる」もしくは「×」に修正
上記のように修正していただくといいかと思いました。
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/f7fe1c20b8d3d2f6b71a16f266be8c47.png)](https://startup-technology.gyazo.com/f7fe1c20b8d3d2f6b71a16f266be8c47)
4. メモ一覧画面も日本語で統一するといいかと！
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/00746fbd2be79e2a35e787a4d8b73190.png)](https://startup-technology.gyazo.com/00746fbd2be79e2a35e787a4d8b73190)

**Comment by yu-ka3028** [comment]
お疲れ様です！
画像付きで丁寧なレビューありがとうございます...!!
ご指摘いただけた箇所の修正をいたしました。
お忙しいところ恐れ入ります、ご確認お願いいたします。

---

## 概要

- レビュー２訂正

## 実装内容
- 変更点
  - [x] usernameをuniqに変更
  - [x] メモ作成モーダルのデザイン修正
  - [x] フッターに隠れるページの修正 
  - [x] 日本語表記  
 
- 追加変更部分
  - [x] メモ一覧/振り返りメモ一覧のフッダーによる隠れ部分修正

## 備考

**Comment by tmtkzk0823** [comment]
確認しました！ありがとうございます！
　
以下、追加のレビューです！（アプリに統一感を出したいため少々レビューの回数が重なるかとと思います🙇‍♂️）

1. エラー文の日本語化対応をおねがいします！
 [![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/29d75d76adc0e124d8ecc9b61ae75c29.png)](https://startup-technology.gyazo.com/29d75d76adc0e124d8ecc9b61ae75c29)

2. メモを入力する時、フォームが非アクティブ状態だと枠が見えず、どこに入力すればいいのかが伝わりにくいので、CSS等で枠を常に表示してあげてもいいかと思います！（入力フォーム全てお願いできればと！）
[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/e067c79b4f8a6601b21e4bdb1521b1b3.gif)](https://startup-technology.gyazo.com/e067c79b4f8a6601b21e4bdb1521b1b3)

3. [![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/8b4b87cba05aea7b08073af8f72af6e4.png)](https://startup-technology.gyazo.com/8b4b87cba05aea7b08073af8f72af6e4)

**Comment by yu-ka3028** [comment]
お疲れ様です！
ご指摘いただけた箇所の修正をいたしました。
お忙しいところ恐れ入ります、ご確認お願いいたします。

---

## 概要

- レビュー３訂正

## 実装内容
- 変更点
  - [x] フラッシュメッセージ/ボタンなど英語→日本語
  - [x] 振り返りメモ/先週の振り返りメモページに背景追加
  - [x] タグ更新をボタンへ変更
  - [x] memo#indexチェックボックスの高さ修正

 
- 追加変更部分
  - [x] 振り返りメモ/先週の振り返りメモ：振り返り一覧へ戻るボタン設置

## 備考

**Comment by yu-ka3028** [comment]
お疲れ様です！
ご指摘いただけた箇所の修正をいたしました。
お忙しいところ恐れ入ります、ご確認お願いいたします。

---

## 概要

- レビュー４訂正

## 実装内容
- 変更点
  - 背景が見づらかったため、単色に変更しました
    - [x] 背景を単色に統一し、全面にかかるよう修正(memo#index/show/lastweek, ref_memo#index/show)

- 追加変更部分
  - [x] タグ絞り込み検索にplaceholderタグを設定
  - [x] 検索ボタン背景着色

## 備考

**Comment by tmtkzk0823** [comment]
確認しました！
以下の画像の部分も対応お願いしてもいいでしょうか？

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/77ad9af33e950f72a2f15050c0b3301a.png)](https://startup-technology.gyazo.com/77ad9af33e950f72a2f15050c0b3301a)

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/4f459d1e856f8e72536068a9cc2380f7.png)](https://startup-technology.gyazo.com/4f459d1e856f8e72536068a9cc2380f7)

**Comment by yu-ka3028** [comment]
お疲れ様です！
ワイドサイズの確認しておりませんでした...!!
抜け漏れ多く申し訳ございません...!!
修正いたしました！

お忙しいところ恐れ入ります、ご確認お願いいたします。

---

## 概要

- レビュー５訂正

## 実装内容
- 変更点
  - [x] ref_memo#index：背景と要素の大きさずれ（ワイドサイズで確認）
  - [x] ref_memo#new：タイトル「先週の振り返りメモ」→「振り返りメモ」
  - [x] ref_memo#new：背景画像→他と統一 

- 追加変更部分
  - [x] memo#show：幅を大きく変更

## 備考
